"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { addDays, format } from "date-fns";
import { Eye, FileCheck2, Plus, Save, Trash2, X } from "lucide-react";
import { useState, useTransition } from "react";
import { useFieldArray, useForm, useWatch, type Resolver } from "react-hook-form";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import type { Product, Invoice, InvoiceItem } from "@/lib/db/schema";
import { INVOICE_STATUSES, PAYMENT_METHODS } from "@/lib/constants";
import { invoiceSchema, type InvoiceInput } from "@/lib/validation/invoice";
import { calculateLine, formatMoney } from "@/lib/money";
import { saveInvoiceAction } from "@/app/(app)/factures/actions";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input, Select, Textarea } from "@/components/ui/input";
import { ProductSelector } from "./product-selector";
import { InvoiceTotals } from "./invoice-totals";

type EditableInvoice=Invoice&{items:InvoiceItem[]};
const blankItem={productId:null,productReference:"",productName:"",description:"",quantity:1,unit:"PIECE" as const,unitPriceHt:0,discountRate:0,vatRate:20};
function defaults(invoice?:EditableInvoice|null):InvoiceInput{
  if(!invoice)return{invoiceDate:format(new Date(),"yyyy-MM-dd"),dueDate:format(addDays(new Date(),30),"yyyy-MM-dd"),clientName:"",clientIce:"",clientIf:"",clientAddress:"",clientCity:"",clientPhone:"",clientEmail:"",paymentMethod:"BANK_TRANSFER",status:"UNPAID",notes:"",items:[blankItem]};
  return{invoiceDate:invoice.invoiceDate,dueDate:invoice.dueDate||"",clientName:invoice.clientName,clientIce:invoice.clientIce||"",clientIf:invoice.clientIf||"",clientAddress:invoice.clientAddress||"",clientCity:invoice.clientCity||"",clientPhone:invoice.clientPhone||"",clientEmail:invoice.clientEmail||"",paymentMethod:invoice.paymentMethod as InvoiceInput["paymentMethod"],status:invoice.status as InvoiceInput["status"],notes:invoice.notes||"",items:invoice.items.map(i=>({productId:i.productId,productReference:i.productReference||"",productName:i.productName,description:i.description||"",quantity:Number(i.quantity),unit:i.unit as InvoiceInput["items"][number]["unit"],unitPriceHt:Number(i.unitPriceHt),discountRate:Number(i.discountRate),vatRate:Number(i.vatRate)}))};
}

function Field({label,error,style,children}:{label:string;error?:string;style?:React.CSSProperties;children:React.ReactNode}){return <div className="field" style={style}><label>{label}</label>{children}{error&&<span className="field-error">{error}</span>}</div>}

function Preview({data,currency,onClose}:{data:InvoiceInput;currency:string;onClose:()=>void}){return <div style={{position:"fixed",inset:0,zIndex:100,background:"#000b",overflow:"auto",padding:20}}><div style={{maxWidth:920,margin:"0 auto 20px",display:"flex",justifyContent:"flex-end"}}><Button variant="secondary" onClick={onClose}><X size={17}/>Fermer l’aperçu</Button></div><div className="invoice-paper"><div style={{display:"flex",justifyContent:"space-between",gap:30,marginBottom:40}}><div><div style={{fontWeight:800,fontSize:20,color:"#8a631c"}}>OUDAROUR FOOD</div><p style={{color:"#777",marginTop:7}}>SOCIETE OUDAROUR FOOD SARL</p></div><div style={{textAlign:"right"}}><h1 style={{fontSize:30,margin:0}}>FACTURE</h1><p style={{color:"#777"}}>Numéro généré à l’enregistrement</p></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:30,marginBottom:30}}><div><small style={{color:"#777",textTransform:"uppercase"}}>Facturé à</small><h3 style={{margin:"6px 0"}}>{data.clientName||"Client"}</h3><p>{data.clientAddress}<br/>{data.clientCity}</p></div><div style={{textAlign:"right"}}><p>Date : <strong>{data.invoiceDate}</strong></p>{data.dueDate&&<p>Échéance : <strong>{data.dueDate}</strong></p>}</div></div><table><thead><tr><th>Désignation</th><th>Qté</th><th>Prix HT</th><th>TVA</th><th>Total HT</th></tr></thead><tbody>{data.items.map((i,k)=>{const line=calculateLine(i);return <tr key={k}><td><strong>{i.productName||"Produit"}</strong><br/><small>{i.description}</small></td><td>{i.quantity}</td><td>{formatMoney(i.unitPriceHt,currency)}</td><td>{i.vatRate}%</td><td>{formatMoney(line.totalHt,currency)}</td></tr>})}</tbody></table><div style={{width:330,margin:"28px 0 0 auto"}}><InvoiceTotals items={data.items} currency={currency} document showWords/></div></div></div>}

export function InvoiceForm({products,currency="MAD",defaultVat=20,invoice}:{products:Product[];currency?:string;defaultVat?:number;invoice?:EditableInvoice|null}){
  const router=useRouter();const[pending,start]=useTransition();const[preview,setPreview]=useState<InvoiceInput|null>(null);
  const form=useForm<InvoiceInput>({resolver:zodResolver(invoiceSchema) as Resolver<InvoiceInput>,defaultValues:defaults(invoice),mode:"onBlur"});const{register,control,setValue,getValues,handleSubmit,formState:{errors}}=form;const{fields,append,remove}=useFieldArray({control,name:"items"});const items=useWatch({control,name:"items"})||[];
  const persist=(data:InvoiceInput,status?:InvoiceInput["status"])=>start(async()=>{const result=await saveInvoiceAction(invoice?.id||null,{...data,status:status||data.status});if(result.success){toast.success(result.message);router.push(`/factures/${result.id}`);router.refresh()}else toast.error(result.message)});
  const submitWith=(status?:InvoiceInput["status"])=>handleSubmit(data=>persist(data,status),()=>toast.error("Vérifiez les champs signalés."))();
  return <><form onSubmit={handleSubmit(data=>persist(data))}><div className="invoice-layout"><div className="invoice-stack">
    <Card className="section-card"><h2 className="section-title">Informations facture</h2><div className="grid-form"><Field label="Date de facture" error={errors.invoiceDate?.message} style={{gridColumn:"span 3"}}><Input type="date" {...register("invoiceDate")}/></Field><Field label="Date d’échéance" error={errors.dueDate?.message} style={{gridColumn:"span 3"}}><Input type="date" {...register("dueDate")}/></Field><Field label="Mode de paiement" style={{gridColumn:"span 3"}}><Select {...register("paymentMethod")}>{Object.entries(PAYMENT_METHODS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></Field><Field label="Statut" style={{gridColumn:"span 3"}}><Select {...register("status")}>{Object.entries(INVOICE_STATUSES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></Field></div><p style={{margin:"14px 0 0",color:"var(--muted)",fontSize:12.5}}>Le numéro sera généré lors de l’enregistrement.</p></Card>
    <Card className="section-card"><h2 className="section-title">Client</h2><div className="grid-form"><Field label="Nom / Raison sociale *" error={errors.clientName?.message} style={{gridColumn:"span 6"}}><Input {...register("clientName")} placeholder="Nom du client ou société"/></Field><Field label="ICE" style={{gridColumn:"span 3"}}><Input {...register("clientIce")}/></Field><Field label="IF" style={{gridColumn:"span 3"}}><Input {...register("clientIf")}/></Field><Field label="Adresse" style={{gridColumn:"span 6"}}><Input {...register("clientAddress")}/></Field><Field label="Ville" style={{gridColumn:"span 3"}}><Input {...register("clientCity")}/></Field><Field label="Téléphone" style={{gridColumn:"span 3"}}><Input {...register("clientPhone")}/></Field><Field label="Email" error={errors.clientEmail?.message} style={{gridColumn:"span 6"}}><Input type="email" {...register("clientEmail")}/></Field></div></Card>
    <Card><div style={{padding:"18px 20px",display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px solid var(--border)"}}><div><h2 className="section-title" style={{margin:0}}>Produits de la facture</h2><small style={{color:"var(--muted)"}}>{fields.length} ligne{fields.length>1?"s":""}</small></div><Button type="button" size="sm" variant="secondary" onClick={()=>append({...blankItem,vatRate:defaultVat})}><Plus size={16}/>Ajouter un produit</Button></div>
      {errors.items?.root?.message&&<p className="field-error" style={{padding:"0 20px"}}>{errors.items.root.message}</p>}
      <div className="invoice-items-table table-wrap"><table className="data-table" style={{minWidth:1100}}><thead><tr><th style={{width:260}}>Produit</th><th>Description</th><th>Quantité</th><th>Prix HT</th><th>Remise</th><th>TVA</th><th>Total HT</th><th></th></tr></thead><tbody>{fields.map((field,index)=>{const item=items[index]||blankItem;const line=calculateLine(item);return <tr key={field.id}><td><input type="hidden" {...register(`items.${index}.productId`)}/><input type="hidden" {...register(`items.${index}.productName`)}/><input type="hidden" {...register(`items.${index}.productReference`)}/><input type="hidden" {...register(`items.${index}.unit`)}/><ProductSelector products={products} value={item.productId} onSelect={p=>{setValue(`items.${index}.productId`,p.id);setValue(`items.${index}.productReference`,p.reference);setValue(`items.${index}.productName`,p.name);setValue(`items.${index}.description`,p.description||"");setValue(`items.${index}.unit`,p.unit as InvoiceInput["items"][number]["unit"]);setValue(`items.${index}.unitPriceHt`,Number(p.priceHt));setValue(`items.${index}.vatRate`,Number(p.vatRate))}}/></td><td><Input {...register(`items.${index}.description`)}/></td><td><Input type="number" min="0.001" step="0.001" {...register(`items.${index}.quantity`,{valueAsNumber:true})}/></td><td><Input type="number" min="0" step="0.01" {...register(`items.${index}.unitPriceHt`,{valueAsNumber:true})}/></td><td><Input type="number" min="0" max="100" step="0.01" {...register(`items.${index}.discountRate`,{valueAsNumber:true})}/></td><td><Input type="number" min="0" max="100" step="0.01" {...register(`items.${index}.vatRate`,{valueAsNumber:true})}/></td><td><strong>{formatMoney(line.totalHt,currency)}</strong></td><td><Button type="button" variant="ghost" size="icon" disabled={fields.length===1} onClick={()=>remove(index)}><Trash2 size={16}/></Button></td></tr>})}</tbody></table></div>
      <div className="invoice-item-cards" style={{display:"none",padding:14}}>{fields.map((field,index)=>{const item=items[index]||blankItem;const line=calculateLine(item);return <div className="card section-card" key={field.id}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><strong>Produit {index+1}</strong><Button type="button" variant="ghost" size="icon" disabled={fields.length===1} onClick={()=>remove(index)}><Trash2 size={16}/></Button></div><input type="hidden" {...register(`items.${index}.productId`)}/><input type="hidden" {...register(`items.${index}.productName`)}/><input type="hidden" {...register(`items.${index}.productReference`)}/><input type="hidden" {...register(`items.${index}.unit`)}/><div className="field"><label>Produit</label><ProductSelector products={products} value={item.productId} onSelect={p=>{setValue(`items.${index}.productId`,p.id);setValue(`items.${index}.productReference`,p.reference);setValue(`items.${index}.productName`,p.name);setValue(`items.${index}.description`,p.description||"");setValue(`items.${index}.unit`,p.unit as InvoiceInput["items"][number]["unit"]);setValue(`items.${index}.unitPriceHt`,Number(p.priceHt));setValue(`items.${index}.vatRate`,Number(p.vatRate))}}/></div><div className="grid-form" style={{marginTop:12}}><Field label="Description" style={{gridColumn:"span 12"}}><Input {...register(`items.${index}.description`)}/></Field><Field label="Quantité" style={{gridColumn:"span 6"}}><Input type="number" step="0.001" {...register(`items.${index}.quantity`,{valueAsNumber:true})}/></Field><Field label="Prix HT" style={{gridColumn:"span 6"}}><Input type="number" step="0.01" {...register(`items.${index}.unitPriceHt`,{valueAsNumber:true})}/></Field><Field label="Remise %" style={{gridColumn:"span 6"}}><Input type="number" {...register(`items.${index}.discountRate`,{valueAsNumber:true})}/></Field><Field label="TVA %" style={{gridColumn:"span 6"}}><Input type="number" {...register(`items.${index}.vatRate`,{valueAsNumber:true})}/></Field></div><div style={{display:"flex",justifyContent:"space-between",marginTop:14,paddingTop:12,borderTop:"1px solid var(--border)"}}><span>Total HT</span><strong>{formatMoney(line.totalHt,currency)}</strong></div></div>})}</div>
    </Card>
    <Card className="section-card"><h2 className="section-title">Notes</h2><Textarea {...register("notes")} placeholder="Informations complémentaires visibles sur la facture…"/></Card>
  </div><aside className="card section-card totals-card"><h2 className="section-title">Récapitulatif</h2><InvoiceTotals items={items} currency={currency}/><div className="desktop-only" style={{flexDirection:"column",gap:9,marginTop:22}}><Button type="submit" disabled={pending}><Save size={17}/>{pending?"Enregistrement…":"Enregistrer"}</Button><Button type="button" variant="secondary" disabled={pending} onClick={()=>submitWith("DRAFT")}><FileCheck2 size={17}/>Enregistrer comme brouillon</Button><Button type="button" variant="ghost" onClick={()=>setPreview(getValues())}><Eye size={17}/>Aperçu</Button><Button type="button" variant="ghost" onClick={()=>router.back()}>Annuler</Button></div></aside></div><div className="mobile-actions"><Button type="button" variant="secondary" onClick={()=>setPreview(getValues())}><Eye size={17}/>Aperçu</Button><Button type="button" onClick={()=>submitWith()} disabled={pending}><Save size={17}/>{pending?"…":"Enregistrer"}</Button></div></form>{preview&&<Preview data={preview} currency={currency} onClose={()=>setPreview(null)}/>}</>;
}
