"use client";
import { Save } from "lucide-react";
import { useTransition } from "react";
import { toast } from "sonner";
import type { CompanySettings } from "@/lib/db/schema";
import { saveSettingsAction } from "@/app/(app)/parametres/actions";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input, Textarea } from "@/components/ui/input";

function Field({label,children,span=4}:{label:string;children:React.ReactNode;span?:number}){return <div className="field" style={{gridColumn:`span ${span}`}}><label>{label}</label>{children}</div>}
export function SettingsForm({settings}:{settings:CompanySettings|Record<string,unknown>}){const s=settings as CompanySettings;const[pending,start]=useTransition();function submit(data:FormData){const input=Object.fromEntries(data.entries());start(async()=>{const r=await saveSettingsAction(input);if(r.success)toast.success(r.message);else toast.error(r.message)})}return <form action={submit} className="invoice-stack">
  <Card className="section-card"><h2 className="section-title">Entreprise</h2><p style={{color:"var(--muted)",margin:"-8px 0 20px"}}>Ces informations apparaissent sur vos factures et documents PDF.</p><div className="grid-form"><Field label="Raison sociale *" span={6}><Input name="companyName" required defaultValue={s.companyName}/></Field><Field label="Nom commercial" span={6}><Input name="tradeName" defaultValue={s.tradeName||""}/></Field><Field label="Logo URL" span={12}><Input type="url" name="logoUrl" defaultValue={s.logoUrl||""} placeholder="https://…"/></Field><Field label="Adresse" span={6}><Input name="address" defaultValue={s.address||""}/></Field><Field label="Ville"><Input name="city" defaultValue={s.city||""}/></Field><Field label="Pays"><Input name="country" defaultValue={s.country||"Maroc"}/></Field><Field label="Capital social"><Input name="capital" defaultValue={s.capital||""} placeholder="Ex. 100 000 MAD"/></Field><Field label="ICE"><Input name="ice" defaultValue={s.ice||""}/></Field><Field label="IF"><Input name="taxId" defaultValue={s.taxId||""}/></Field><Field label="Taxe professionnelle (TP)"><Input name="professionalTax" defaultValue={s.professionalTax||""}/></Field><Field label="RC"><Input name="rc" defaultValue={s.rc||""}/></Field><Field label="CNSS"><Input name="cnss" defaultValue={s.cnss||""}/></Field><Field label="Téléphone"><Input name="phone" defaultValue={s.phone||""}/></Field><Field label="Email"><Input name="email" type="email" defaultValue={s.email||""}/></Field><Field label="Site web" span={6}><Input name="website" type="url" defaultValue={s.website||""}/></Field></div></Card>
  <Card className="section-card"><h2 className="section-title">Facturation</h2><div className="grid-form"><Field label="Préfixe facture"><Input name="invoicePrefix" required defaultValue={s.invoicePrefix||"FAC"} style={{textTransform:"uppercase"}}/></Field><Field label="TVA par défaut (%)"><Input name="defaultVat" type="number" min="0" max="100" step="0.01" defaultValue={s.defaultVat||"20"}/></Field><Field label="Devise"><Input name="currency" defaultValue={s.currency||"MAD"}/></Field><Field label="Conditions de paiement" span={12}><Textarea name="paymentTerms" defaultValue={s.paymentTerms||"Paiement à 30 jours."}/></Field><Field label="Texte de pied de facture" span={12}><Textarea name="invoiceFooter" defaultValue={s.invoiceFooter||"Merci pour votre confiance."}/></Field></div></Card>
  <Card className="section-card"><h2 className="section-title">Paiement</h2><Field label="RIB / Informations bancaires" span={12}><Textarea name="bankDetails" defaultValue={s.bankDetails||""} placeholder="Banque, titulaire, IBAN ou RIB…"/></Field></Card><div style={{display:"flex",justifyContent:"flex-end"}}><Button disabled={pending}><Save size={17}/>{pending?"Enregistrement…":"Enregistrer les paramètres"}</Button></div>
  </form>}
